name: Build ubuntu
on: [push, pull_request]

jobs:
  job_1:
    name: create ubuntu base
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: build image
      run: docker build -t ubuntubase -f base/Dockerfile.ubuntu_20.04.gnu .

    - name: login to dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: push image
      run: |
        docker tag ubuntubase noaaemc/ubuntu-base:v1
        docker push noaaemc/ubuntu-base:v1
